#!/usr/bin/env bash

# STOP systemd resolver daemon
eval $(sudo systemctl stop systemd-resolved.service)
# Configure your local dns resolver to point to optimus
eval $(sed s/127.0.0.53/127.0.0.1/g /run/systemd/resolve/stub-resolv.conf > stub-resolv.conf)
eval $(sudo mv stub-resolv.conf /run/systemd/resolve/stub-resolv.conf)

sudo $(which optimus) "$@"

